# Generated by Django 4.1.1 on 2022-09-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='agree',
        ),
    ]
